
const TEAM_FLAG_FILES = {
  'México': 'mexico',
  'Sudáfrica': 'Sudáfrica',
  'Corea del Sur': 'south_korea',
  'Chequia': 'czech_republic',
  'Canadá': 'canada',
  'Bosnia y Herzegovina': 'bosnia',
  'Catar': 'qatar',
  'Suiza': 'switzerland',
  'Brasil': 'brazil',
  'Marruecos': 'morocco',
  'Haití': 'haiti',
  'Escocia': 'scotland',
  'Estados Unidos': 'united_states',
  'Paraguay': 'paraguay',
  'Australia': 'australia',
  'Turquía': 'turkey',
  'Alemania': 'germany',
  'Curazao': 'curacao',
  'Costa de Marfil': 'cotedivoire',
  'Ecuador': 'ecuador',
  'Países Bajos': 'netherlands',
  'Japón': 'japan',
  'Suecia': 'sweden',
  'Túnez': 'tunisia',
  'Bélgica': 'belgium',
  'Egipto': 'egypt',
  'Irán': 'iran',
  'Nueva Zelanda': 'new_zealand',
  'España': 'spain',
  'Cabo Verde': 'CapeVerde',
  'Arabia Saudita': 'saudi_arabia',
  'Uruguay': 'uruguay',
  'Francia': 'france',
  'Senegal': 'senegal',
  'Irak': 'iraq',
  'Noruega': 'norway',
  'Argentina': 'argentina',
  'Argelia': 'algeria',
  'Austria': 'austria',
  'Jordania': 'jordan',
  'Portugal': 'portugal',
  'RD del Congo': 'democratic_republic_of_the_congo',
  'Uzbekistán': 'uzbekistan',
  'Colombia': 'colombia',
  'Inglaterra': 'england',
  'Croacia': 'croatia',
  'Ghana': 'ghana',
  'Panamá': 'panama',
};

export function getTeamFlagSrc(teamName = '') {
  const fileName = TEAM_FLAG_FILES[teamName];
  return fileName ? `/flags/${fileName}.png` : null;
}
